Fix kernel signature due to AMD compiler error
The following error did not show up in the CPU OpenCL

error: kernel arguments can't be declared with
          types
          bool/half/size_t/ptrdiff_t/intptr_t/uintptr_t/pointer-to-pointer
                            ElembyElem *elembyelem,
                                        ^